[package]
name = "input"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]

[dependencies]
sdl2.workspace = true
gameplay.workspace = true
nanoserde.workspace = true
