[package]
name = "render-opengl"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "../../build.rs"

[dependencies]
glam.workspace = true
gameplay.workspace = true
render-target.workspace = true

[dev-dependencies]
wad.workspace = true
